name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Install Newman
        run: npm install -g newman
      - name: Install dependencies
        run: npm ci
      - name: Start the server
        run: nohup npm run start &
      - name: Run API tests
        run: npm run api-test

  # cypress_tests:
  #   needs: api_tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         start: npm start
  #         wait-on: 'http://localhost:3000'
  #         wait-on-timeout: 300

  # deployment:
  # needs: [api_tests, cypress_tests]
  # if: success()
  # runs-on: ubuntu-latest
  # steps:
  #   - uses: actions/checkout@v2
  #   - with:
  #       ref: main
  #   - name: Deploy to Server via SCP
  #     uses: appleboy/scp-action@v0.1.4
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USER }}
  #       key: ${{ secrets.SSH_KEY }}
  #       source: "*.*"
  #       target: "/var/www/github-actions-example/"
